namespace StaffApi.Models.Entities
{
    public class Salary_Entities
    {
        public int ID { get; set; }
        public decimal EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string FULLNAME { get; set; }
        public string ID_NUMBER { get; set; }
        public int SECTION_ID { get; set; }
        public string SECTION_NAME_EN { get; set; }
        public int DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_NAME_EN { get; set; }
        public int DIVISION_ID { get; set; }
        public string DIVISION_NAME_EN { get; set; }
        public int JOBTITLE_ID { get; set; }
        public string JOBTITLE_NAME_EN { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public string E_LEVEL { get; set; }
        public string TAX_NUMBER { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string BANK_NAME { get; set; }
        public string PAY_DAY { get; set; }
        public decimal BASIC_SALARY { get; set; }
        public decimal MIN_SALARY { get; set; }
        public double HOUR_WORK { get; set; }
        public double PER { get; set; }
        public double DAY_WORK { get; set; }
        public decimal PAY_MONTH { get; set; }
        public double DW_PRO1 { get; set; }
        public decimal PAY_DWPRO1 { get; set; }
        public double DW_PRO85 { get; set; }
        public decimal PAY_DWPRO85 { get; set; }
        public double LEAVE { get; set; }
        public decimal PAY_LEAVE { get; set; }
        public double HOUR_OT30 { get; set; }
        public double HOUR_OT150 { get; set; }
        public double HOUR_OT195 { get; set; }
        public double HOUR_OT200 { get; set; }
        public double HOUR_OT280 { get; set; }
        public double HOUR_OT300 { get; set; }
        public double HOUR_OT410 { get; set; }
        public decimal PAY_OT30 { get; set; }
        public decimal PAY_OT150 { get; set; }
        public decimal PAY_OT195 { get; set; }
        public decimal PAY_OT200 { get; set; }
        public decimal PAY_OT280 { get; set; }
        public decimal PAY_OT300 { get; set; }
        public decimal PAY_OT410 { get; set; }
        public decimal TOTAL_OT { get; set; }
        public string OT_30 { get; set; }
        public decimal PAY_OT_TAX { get; set; }
        public decimal PAY_OT_NONTAX { get; set; }
        public decimal PAY_LEAVEREMAIN { get; set; }
        public double PREG_LEAVE { get; set; }
        public double COMPENSATION { get; set; }
        public decimal COMPENSATION_PAY { get; set; }
        public double LEAVE_PAID { get; set; }
        public double DAYOFF { get; set; }
        public double LEAVE_OTHER { get; set; }
        public double TOTAL_WORK_DAY { get; set; }
        public double TOTAL_DAY { get; set; }
        public decimal ALL_HOUSE { get; set; }
        public decimal ALL_RESPON { get; set; }
        public decimal ALL_MEAL { get; set; }
        public decimal ALL_OTHER { get; set; }
        public decimal ALL_PETROL { get; set; }
        public decimal ALL_PHONE { get; set; }
        public decimal ALL_ACT { get; set; }
        public decimal ALL_SPEC { get; set; }
        public decimal ALL_SUPPORT { get; set; }
        public decimal TOTAL_ALL { get; set; }
        public decimal TOTAL_ALL_PRO1 { get; set; }
        public decimal TOTAL_ALL_PRO85 { get; set; }
        public decimal BONUS { get; set; }
        public decimal BONUS_OTHER { get; set; }
        public decimal PER_BONUS { get; set; }
        public decimal FULL_PAY { get; set; }
        public decimal ADJUST { get; set; }
        public decimal INCOME_NONTAX { get; set; }
        public decimal DIF_SALARY { get; set; }
        public decimal INCENTIVES { get; set; }
        public decimal TOTAL_PAY { get; set; }
        public decimal ADVANCE { get; set; }
        public bool SOCIAL { get; set; }
        public int C_SOCIAL_PAY { get; set; }
        public int C_MEDICAL_PAY { get; set; }
        public int C_JOB_PAY { get; set; }
        public int C_UNION_PAY { get; set; }
        public int C_INSURANCE { get; set; }
        public int C_UNION { get; set; }
        public int C_ACCIDENT_PAY { get; set; }
        public int AC_SI { get; set; }
        public int E_SOCIAL_PAY { get; set; }
        public int E_MEDICAL_PAY { get; set; }
        public int E_JOB_PAY { get; set; }
        public int UNION_PAY { get; set; }
        public int TOTAL_JOBLESS { get; set; }
        public int TOTAL_SI { get; set; }
        public int TOTAL_SI_E { get; set; }
        public int TOTAL_SI_C { get; set; }
        public int MAX_SI { get; set; }
        public int MAX_JOB { get; set; }
        public int PERSONS { get; set; }
        public decimal FEE { get; set; }
        public bool PROGRESS { get; set; }
        public decimal TAX { get; set; }
        public decimal TAX_SELF { get; set; }
        public double TAX_RATE { get; set; }
        public double TAX_RATE_INPUT { get; set; }
        public decimal AMT { get; set; }
        public decimal MIN_TAX { get; set; }
        public decimal TAX_REFUND { get; set; }
        public decimal TOTAL_REDUCTION { get; set; }
        public decimal TOTAL_OBLIGATION { get; set; }
        public decimal REAL_PAY { get; set; }
        public bool FIX { get; set; }
        public bool QUIT { get; set; }
        public bool PROBATION { get; set; }
        public bool OVERTIME { get; set; }
        public int WARNING_TIME { get; set; }
        public string REMARK { get; set; }
        public decimal BANK_TRANSFER { get; set; }
        public decimal MINUS_OTHER { get; set; }
        public int MINUS_INS { get; set; }
        public decimal SALARY_INS { get; set; }
        public double WD_LUNCH { get; set; }
        public decimal LUNCH_MAX { get; set; }
        public bool NO_LUNCH_MAX { get; set; }
        public decimal GIFT_CARD { get; set; }
        public decimal REFUND { get; set; }
        public decimal TAX_LY { get; set; }
        public decimal GOV_FUNDS { get; set; }
        public string SUB_POSITION { get; set; }
        public decimal TOTAL_ACTUAL_SAL { get; set; }
        public decimal TOTAL_ACTUAL_ALL { get; set; }
        public double SORT_SECTION { get; set; }
        public double SORT_JOB { get; set; }
    }
}
